name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ { dotnet: '2.2', framework: 'netstandard2.0' }, { dotnet: '3.1.x', framework: 'netstandard2.1' }, { dotnet: '5.x.x', framework: 'net5' }, { dotnet: '6.x.x', framework: 'net6' } ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.version.dotnet }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore --framework ${{ matrix.version.framework }}